### ISSUE TITLE
TypeError: output is not a function

### ISSUE THREAD

**Issue by laintin** [TooTallNate/node-vorbis#14]
1 ↵
node_modules/vorbis/lib/encoder.js:169
  output(op_header); // automatically gets placed in its own `ogg_page`
  ^

TypeError: output is not a function
    at Encoder._writeHeader (node_modules/vorbis/lib/encoder.js:169:3)
    at Encoder._transform (node_modules/vorbis/lib/encoder.js:108:10)
    at Encoder.Transform._read (_stream_transform.js:167:10)
    at Encoder.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Encoder.Writable.write (_stream_writable.js:207:11)
    at ReadStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)

**Comment by laintin** [comment]
node version:
v4.2.4

**Comment by loosemoose** [comment]
4.2.4 has a bug with the stream api, upgrade to 4.2.6

**Comment by loosemoose** [comment]
I forked and corrected the issue (https://github.com/loosemoose/node-vorbis), I put up a Pull request. ALso you may want to update to the latest LTS version of node (currently 4.2.6). I had issues with 4.2.4 cutting off the end of my stream (i lost last 6 seconds of a song that was 2:22 long).

**Comment by laintin** [comment]
thank you.
