### ISSUE TITLE
npm install vorbis - broken?

### ISSUE THREAD

**Issue by danryu** [TooTallNate/node-vorbis#26]
For me, the build breaks like this:

> /usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/vorbis.node
g++: error: /path/to/project/node_modules/ogg/build/Release/ogg.node: No such file or directory
make: *** [vorbis.target.mk:145: Release/obj.target/vorbis.node] Error 1
make: Leaving directory '/path/to/project/node_modules/vorbis/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /path/to/project/node_modules/vorbis
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

To work round this, I did:

> cd node_modules/ogg/build/Release/
cp lib.target/ogg.node .

And then 
npm install vorbis
succeeds.

This is just a quick hack to allow me to progress, I'm no Node guru....

**Comment by renanyoy** [comment]
please add a fix nodejs 10 isn't supported anymore..
