### ISSUE TITLE
output(b); string is not a function

### ISSUE THREAD

**Issue by bwiggs** [TooTallNate/node-vorbis#8]
I'm having an issue decoding a ogg-vorbis file. 

```
/Users/brianwigginton/Projects/hal/node_modules/vorbis/lib/decoder.js:135
      output(b);
      ^
TypeError: string is not a function
  at pcmout (/Users/brianwigginton/Projects/hal/node_modules/vorbis/lib/decoder.js:135:7)
  at Decoder._transform (/Users/brianwigginton/Projects/hal/node_modules/vorbis/lib/decoder.js:120:5)
  at Decoder.Transform._read (_stream_transform.js:179:10)
  at Decoder.Transform._write (_stream_transform.js:167:12)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at Decoder.Writable.write (_stream_writable.js:183:11)
  at write (_stream_readable.js:583:24)
  at flow (_stream_readable.js:592:7)
  at DecoderStream.pipeOnReadable (_stream_readable.js:624:5)
  at DecoderStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at DecoderStream.Readable.push (_stream_readable.js:127:10)
  at DecoderStream.onpacket (/Users/brianwigginton/Projects/hal/node_modules/ogg/lib/decoder-stream.js:168:25)
  at DecoderStream.g (events.js:180:16)
  at DecoderStream.EventEmitter.emit (events.js:92:17)
  at afterPacketout (/Users/brianwigginton/Projects/hal/node_modules/ogg/lib/decoder-stream.js:135:12)
```

Running node-inspector I see that `output` is an argument passed into the decoder.

```
Decoder.prototype._transform = function (packet, output, fn)
```

When I go up the call stack it seems that the callee is actually passing in the encoding as the second argument, which from what I can tell is always a string? `output` is set to "buffer".

Any help would be greatly appreciated.

**Comment by loosemoose** [comment]
same here, cannot figure it out.
